# ―――――――――――――――――――――――――――――――――――――――
#
# TitleAPI version 1.0-SNAPSHOT
#
# ―――――――――――――――――――――――――――――――――――――――
messages:
  no-permission: '&cYou dont have permission to this :/'
  only-players: '&cOnly players can execute this command!'
  target-offline: '&cTarget player is offline!'
  test-sent: '&aTest sent to &6{PLAYER}'
  test-title: ':)'
  test-subtitle: '&e:D'

