# ―――――――――――――――――――――――――――――――――――――――
#
# TitleAPI version 1.2
#
# ―――――――――――――――――――――――――――――――――――――――
messages:
  reloaded: '&8> &aConfiguration file reloaded!'
  update-checked: '&8> &aChecked for updates. See console for details...'
  no-permission: '&8> &cYou dont have permission to this :/'
  only-players: '&8> &cOnly players can execute this command!'

