# ―――――――――――――――――――――――――――――――――――――――
#
# TitleAPI version 1.0-SNAPSHOT
#
# ―――――――――――――――――――――――――――――――――――――――
messages:
  no-permission: '&8» &cYou dont have permission to this :/'
  only-players: '&8» &cOnly players can execute this command!'
  target-offline: '&8» &cTarget player is offline!'
  test-sent: '&8» &aTest sent to &6{PLAYER}'
  test-title: '&bTest title!'
  test-subtitle: '&eTest subtitle!!!!'

